name: Package Testing

on:
  workflow_run:
    workflows: ["Checking code style"]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        include:
          # Python 3.10
          - python-version: "3.10"
            django-version: "4.2"
          - python-version: "3.10"
            django-version: "5.2"

          # Python 3.11
          - python-version: "3.11"
            django-version: "4.2"
          - python-version: "3.11"
            django-version: "5.2"

          # Python 3.12
          - python-version: "3.12"
            django-version: "4.2"
          - python-version: "3.12"
            django-version: "5.2"

          # Python 3.13
          - python-version: "3.13"
            django-version: "4.2"
          - python-version: "3.13"
            django-version: "5.2"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Django==${{ matrix.django-version }}
    - name: Build package
      run: |
        bash local_build.sh
    - name: Run Tests
      run: |
        python runtests.py
